filename = input()
f = open(str(filename),"r")
content = f.read()
content.upper();
final_content = content.translate({ ord(c): None for c in "N>" })
f2 = open("test2.txt","w")
f2.write(final_content.upper())
f2.close()
f.close()
#print(content)
